name: Multi-Platform Build and Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.2.2

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV

      - name: Install Project Dependencies
        run: ~/.bun/bin/bun install

      - name: Setup Rust Environment
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install tauri-cli

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Tauri App
        run: alias bun=~/.bun/bin/bun && bun run tauri build

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-app
          path: target/release/bundle/darwin/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Bun
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://bun.sh/install.ps1 -OutFile install.ps1
          .\install.ps1

      - name: Add Bun to PATH
        shell: pwsh
        run: |
          $env:Path += ";C:\Users\runneradmin\.bun\bin"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, "User")

      - name: Install Dependencies
        shell: cmd
        run: C:\Users\runneradmin\.bun\bin\bun.exe install

      - name: Setup Rust and Tauri CLI
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://sh.rustup.rs -OutFile rustup-init.sh
          ./rustup-init.sh -y
          rustup default stable
          rustup component add rust-src
          rustup target add x86_64-pc-windows-msvc
          cargo install tauri-cli

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            C:\Users\runneradmin\.cargo
            C:\Users\runneradmin\.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Tauri App
        shell: pwsh
        run: Set-Alias bun C:\Users\runneradmin\.bun\bin\bun.exe && bun run tauri build

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-app
          path: target/release/bundle/windows/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-0 libclang-dev libgtk-3-0 libappindicator3-1

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV

      - name: Install Project Dependencies
        run: ~/.bun/bin/bun install

      - name: Setup Rust Environment
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install tauri-cli

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            ~/.rustup
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Tauri App
        run: export PATH=$HOME/.bun/bin:$PATH && bun run tauri build

      - name: Show All Artifacts
        run: ls -R target/release/bundle

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux-app
          path: target/release/bundle/tarball/*.tar.gz
