name: Multi-Platform Build and Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.2.2

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV

      - name: Install Project Dependencies
        run: ~/.bun/bin/bun install

      - name: Setup Rust Environment
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install tauri-cli

      - name: Build Tauri App
        run: export PATH=$HOME/.bun/bin:$PATH && bun run tauri build

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: macos-app
          path: src-tauri/target/release/bundle/dmg/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\.cargo
            .\target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Bun
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://bun.sh/install.ps1 -OutFile install.ps1
          .\install.ps1

      - name: Add Bun to PATH
        shell: pwsh
        run: |
          $env:Path += ";C:\Users\runneradmin\.bun\bin"
          [Environment]::SetEnvironmentVariable("Path", $env:Path, "User")
          Write-Output "Current PATH: $env:PATH"
          Get-Command bun -ErrorAction Stop

      - name: Install Dependencies
        shell: cmd
        run: C:\Users\runneradmin\.bun\bin\bun.exe install

      - name: Setup Rust and Tauri CLI
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://sh.rustup.rs -OutFile rustup-init.sh
          ./rustup-init.sh -y
          rustup default stable
          rustup component add rust-src
          rustup target add x86_64-pc-windows-msvc
          cargo install tauri-cli

      - name: Build Tauri App
        shell: pwsh
        run: |
          $env:Path += ";C:\Users\runneradmin\.bun\bin"
          Write-Output "Updated PATH: $env:Path"
          bun run tauri build

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: windows-app
          path: |
            src-tauri/target/release/bundle/nsis/*.exe
            src-tauri/target/release/bundle/msi/*.msi

  build-linux:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            /root/.cargo/registry
            /root/.cargo/git
            /root/.cargo/bin
            /root/.cargo/.package-cache
            ./target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            /root/.bun/install/cache
            /root/.bun/bin
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Dependencies
        run: |
          apt-get update && apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libclang-dev \
            libgtk-3-dev \
            libglib2.0-dev \
            libappindicator3-dev \
            desktop-file-utils \
            libgdk-pixbuf2.0-dev \
            libfuse2 \
            squashfs-tools \
            curl \
            wget \
            git \
            build-essential \
            pkg-config \
            libssl-dev

      - name: Fix FUSE Permissions
        run: |
          echo "user_allow_other" > /etc/fuse.conf
          echo "export LINUXDEPLOY_FUSE=1" >> $GITHUB_ENV

      - name: Force Download linuxdeploy
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          mv linuxdeploy-x86_64.AppImage /usr/local/bin/linuxdeploy

      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "export PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV

      - name: Install Project Dependencies
        run: ~/.bun/bin/bun install

      - name: Setup Rust Environment
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install tauri-cli

      - name: Build Tauri App
        env:
          LINUXDEPLOY_SKIP_APPSTREAM_VALIDATION: 1
          RUST_LOG: debug
        run: export PATH=$HOME/.bun/bin:$PATH && bun run tauri build

      - name: Show All Artifacts
        run: ls -R src-tauri/target/release/bundle

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: linux-app
          path: |
            src-tauri/target/release/bundle/rpm/*.rpm
            src-tauri/target/release/bundle/deb/*.deb